// Dyalisis build script — compile source modular (React + shadcn-style + Cytoscape)
// menjadi SATU file HTML mandiri (CSS + JS inline).
//   node build.mjs [--content ./src/data/nama-app.js] [--out ./dist/index.html]
import { build } from 'esbuild';
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
// Ambil nilai flag hanya bila flag benar-benar ada; jika tidak, indexOf = -1 dan
// args[indexOf+1] akan salah menangkap args[0] (bug: --content jadi output path).
const flagValue = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : undefined;
};
const contentArg = flagValue('--content');
const outArg = flagValue('--out');

// Default = example.js (content demo generik yang ikut di-ship bersama framework).
// Framework tidak bergantung pada data aplikasi apa pun; ganti via `--content`.
const CONTENT = contentArg ? resolve(contentArg) : resolve(__dirname, 'src/data/example.js');
const OUT = outArg ? resolve(outArg) : resolve(__dirname, 'dist/index.html');

console.log(`[dyalisis] content : ${CONTENT}`);
console.log(`[dyalisis] output  : ${OUT}`);

// 1. Pasang content layer ke src/content.js (engine tidak tahu aplikasi apa —
//    content sepenuhnya detachable, tinggal ganti file data).
const contentJs = `// GENERATED by build.mjs — jangan edit manual.
export * from ${JSON.stringify(CONTENT.replace(/\\/g, '/'))};
`;
writeFileSync(resolve(__dirname, 'src/content.js'), contentJs);

// 2. Bundle engine + deps (React, ReactDOM, cytoscape, extensions, elkjs) → dist/bundle.js
await build({
  entryPoints: [resolve(__dirname, 'src/index.jsx')],
  outfile: resolve(__dirname, 'dist/bundle.js'),
  bundle: true,
  minify: true,
  format: 'iife',
  target: ['es2020', 'chrome90', 'firefox90', 'safari14'],
  alias: {
    // cytoscape-elk meng-require("elkjs") → entry Node (lib/main.js) memakai worker
    // fallback browser. Paksa ke elk.bundled.js (single-file, tanpa worker) —
    // file yang sama dengan CDN tervalidasi.
    elkjs: resolve(__dirname, 'node_modules/elkjs/lib/elk.bundled.js')
  },
  logLevel: 'info'
});

// 3. Compile Tailwind (content scan src + template) → dist/styles.css
const tailwindCli = resolve(__dirname, 'node_modules/tailwindcss/lib/cli.js');
execSync(
  `node "${tailwindCli}" -i "${resolve(__dirname, 'src/styles.css')}" ` +
  `-o "${resolve(__dirname, 'dist/styles.css')}" --minify`,
  { stdio: 'inherit', cwd: __dirname }
);

// 4. Inline ke template → output final single .html
const template = readFileSync(resolve(__dirname, 'template.html'), 'utf8');
const css = readFileSync(resolve(__dirname, 'dist/styles.css'), 'utf8');
const js = readFileSync(resolve(__dirname, 'dist/bundle.js'), 'utf8');

mkdirSync(dirname(OUT), { recursive: true });
const html = template
  .replace('<!--DYALISIS_CSS-->', () => `<style>${css}</style>`)
  .replace('<!--DYALISIS_JS-->', () => `<script>${js}<\/script>`)
  .replace('DYALISIS_APP_NAME', () => {
    try {
      const raw = readFileSync(CONTENT, 'utf8');
      const m = /export const APP\s*=\s*\{[^}]*name:\s*['"]([^'"]+)['"]/.exec(raw);
      return m ? m[1] : 'Dyalisis';
    } catch { return 'Dyalisis'; }
  });

writeFileSync(OUT, html);
console.log(`[dyalisis] DONE → ${OUT} (${(html.length / 1024).toFixed(0)} KB)`);